name: CI
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  lint-build-test:
    name: Lint, Build, Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x, 16.x, 14.x, 12.x, 10.x]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test
